// @env ../http-client.env.json

POST {{ host }}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "luffy.monkey@ems.com",
  "password": "password"
}
###

POST {{ host }}/api/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

###
