version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      # Laravel likes these env vars for permission fixing sometimes
      # adjust as needed
      COMPOSER_ALLOW_SUPERUSER: 1
    working_dir: /var/www/html