version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    environment:
      # Laravel likes these env vars for permission fixing sometimes
      # adjust as needed
      COMPOSER_ALLOW_SUPERUSER: 1
    working_dir: /var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: