version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      # Laravel likes these env vars for permission fixing sometimes
      # adjust as needed
      COMPOSER_ALLOW_SUPERUSER: 1
    working_dir: /var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ems
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ems_test
    ports:
      - "5433:5432"
    volumes:
      - db_test:/var/lib/postgresql/data

volumes:
  db:
  db_test: