// @env ../http-client.env.json

POST {{ host }}/api/supplier/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "luffy.monkey@ems.com",
    "password": "password"
}
###

POST {{ host }}/api/supplier/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

###
