POST {{ host }}/api/events
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "asdf",
  "type": "WEDDING",
  "notes": "",
  "schedule": {
    "first": {
      "date": "2026-01-01 00:00:00",
      "guestsCount": null,
      "address": {
        "line1": "123",
        "line2": null,
        "city": "Pasig City",
        "state": "Metro Manila",
        "zip": "1610",
        "lat": null,
        "long": null
      }
    },
    "second": {
      "date": "2026-01-01 00:00:00",
      "guestsCount": 150,
      "address": {
        "line1": "123",
        "line2": null,
        "city": "Pasig City",
        "state": "Metro Manila",
        "zip": "1610",
        "lat": null,
        "long": null
      }
    }
  },
  "client": {
    "firstName": "Kevin",
    "lastName": "Cotongco",
    "password": "password",
    "email": "cotongcokevin@gmail.com",
    "address": {
      "line1": "123",
      "line2": null,
      "city": "Pasig City",
      "state": "Metro Manila",
      "zip": "1610",
      "lat": null,
      "long": null
    },
    "contactNumber": ""
  },
  "celebrant": {
    "first": {
      "title": "Groom",
      "firstName": "Kevin",
      "lastName": "Cotongco",
      "contactNumber": "",
      "address": {
        "line1": "123",
        "line2": null,
        "city": "Pasig City",
        "state": "Metro Manila",
        "zip": "1610",
        "lat": null,
        "long": null
      }
    },
    "second": {
      "title": "BRIDE",
      "firstName": "Rhoma",
      "lastName": "Cabacungan",
      "contactNumber": "",
      "address": {
        "line1": "123",
        "line2": null,
        "city": "Pasig City",
        "state": "Metro Manila",
        "zip": "1610",
        "lat": null,
        "long": null
      }
    }
  }
}