POST {{ host }}/api/events
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "",
  "type": "",
  "notes": "",
  "client": {
    "firstName": "",
    "lastName": "",
    "email": "",
    "address": {
      "line1": "",
      "line2": null,
      "city": "",
      "state": "",
      "zip": "",
      "lat": null,
      "long": null
    },
    "contactNumber": ""
  },
  "celebrant": {
    "one": {
      "title": "",
      "firstName": "",
      "lastName": "",
      "contactNumber": "",
      "address": {
        "line1": "",
        "line2": null,
        "city": "",
        "state": "",
        "zip": "",
        "lat": null,
        "long": null
      }
    },
    "two": {
      "title": "",
      "firstName": "",
      "lastName": "",
      "contactNumber": "",
      "address": {
        "line1": "",
        "line2": null,
        "city": "",
        "state": "",
        "zip": "",
        "lat": null,
        "long": null
      }
    }
  }
}