// @env ../http-client.env.json

POST {{ host }}/api/admin/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "naruto.uzumaki@ems.com",
  "password": "password"
}
###

POST {{ host }}/api/admin/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ token }}

###