name: Pint Lint with reviewdog

on:
  pull_request:
    branches: [main]

jobs:
  pint-reviewdog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-scripts

      - name: Run Pint with reviewdog
        uses: reviewdog/action-php-cs-fixer@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          level: error
          php_cs_fixer_flags: --diff --dry-run